# Masina nr.1: 
#	Hostname: proxy
#	CPU: 1
#	RAM: 1GB
#	IP: 10.143.20.2
#	OS-ul sa aiba toate update-urile instalate.
#	Instalati nginx

# Masina nr.2:
#	Hostname: web
#	CPU: 1
#	RAM: 1GB
#	IP: 10.143.20.3
#	OS-ul sa aiba toate update-urile instalate.
#	Instalati git si golang

# Masina nr.3:
#	Hostname: db
#	CPU: 1
#	RAM: 1GB
#	IP: 10.143.20.4
#	OS-ul sa aiba toate update-urile instalate.
#	Instalati postgresql

# Masina nr.4:
#	Hostname: monitor
#	CPU: 1 
#	RAM: 1GB
#	IP: 10.143.20.5
#	OS-ul sa aiba toate update-urile instalate.
#	Instalati httpd
	


Vagrant.configure("2") do |config|
	
	# variables
	os = "centos/7"
	net = "10.143.20"
  	
	# default provider
	config.vm.provider "libvirt"  

	config.vm.define :proxy do |proxy_config| 
    		
		proxy_config.vm.host_name = 'proxy'
                proxy_config.vm.box = "#{os}"		
                proxy_config.vm.network :private_network, :ip =>'10.143.20.2'

		proxy_config.vm.provider :libvirt do |lv|
	
			lv.memory = 1024
        		lv.cpus = 1
			lv.driver = "kvm"
        		lv.username = "root"
			lv.password = "root"
    		end
		
		config.vm.provision "shell", path: "proxy.sh"
  
  	end

	config.vm.define :web do |web_config| 
    		
		web_config.vm.host_name = 'web'
                web_config.vm.box = "#{os}"		
		web_config.vm.network :private_network, :ip =>'10.143.20.3'

		web_config.vm.provider :libvirt do |lv|
	
			lv.memory = 1024
        		lv.cpus = 1
			lv.driver = "kvm"
        		lv.username = "root"
			lv.password = "root"
    		end
		
		config.vm.provision "shell", path: "web.sh"
  
  	end
	
	config.vm.define :db do |db_config| 
    		
		db_config.vm.host_name = 'db'
                db_config.vm.box = "#{os}"		
		db_config.vm.network :private_network, :ip =>'10.143.20.3'

		db_config.vm.provider :libvirt do |lv|
	
			lv.memory = 1024
        		lv.cpus = 1
			lv.driver = "kvm"
        		lv.username = "root"
			lv.password = "root"
    		end
		
		config.vm.provision "shell", path: "db.sh"
  
  	end

	config.vm.define :monitor do |monitor_config| 
    		
		monitor_config.vm.host_name = 'monitor'
                monitor_config.vm.box = "#{os}"		
		monitor_config.vm.network :private_network, :ip =>'10.143.20.5'

		monitor_config.vm.provider :libvirt do |lv|
	
			lv.memory = 1024
        		lv.cpus = 1
			lv.driver = "kvm"
        		lv.username = "root"
			lv.password = "root"
    		end
		
		monitor_config.vm.provision "shell", inline: <<-SHELL
    		 	yum -y update
		 	yum -y install httpd
		SHELL

		config.vm.provision "shell", path: "monitor.sh"
  
  	end

end
