Vagrant.configure('2') do |config|

	# default provider
	config.vm.provider "libvirt"
	
	config.vm.define :my_vm do |myvm| 
    		
		myvm.vm.host_name = 'myvm'
        myvm.vm.box = 'generic/ubuntu1604'
  		myvm.vm.network :private_network, ip: '10.143.20.10'

		myvm.vm.provider :libvirt do |lv|
			lv.driver = "kvm"
    	end
		
		myvm.vm.provision "shell",
    		inline: "echo \"echo root profile processed\" > ~/.bash_profile"
  	end

end