- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
   - name: Install Python
     raw: test -e /usr/bin/python || (apt -y update && apt  install -y python)
   
   - name: ensure workshop user is on the box
     user:
       state: present
       name: workshop
       shell: /bin/bash
       groups: sudo

   - name: ensure my user’s public key is present in authorized_keys
     authorized_key:
       user: workshop
       key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3DmXNR1rP+CGfMmwcowd4wN9uf6lKaN++9SyowsOmVQyY+x1jlka4rFUxljDrbJLyTmmdwH4fcOs/6ixZlMnNkbYcC48F8YrHWZ6lcheak52q365NRViooG+LuVZU81DOv/+roY0eTBTs6d/mlRC8Us11kpKrtWi7zvFiv7Ld25Uo5yMPOxvDigJzrO0byVefq001mx5EEfDn9uH7nWU/e3wOIDls5kYtEWuI1QHWyOrbLe8O+YiHznBjWa2r6dCobr8KfyfwBuHy4PxS4f17GJ9kGQXWOrVOjMJiblkHndQ5dMn8hQAt6Vir0EJL3XFE0xox9oqxV/LCH9lHc6mj workshop
       state: present