- name: Configure rsyslog
  copy: 
    src: /home/marius/Yonder/Vagrant/proxy/rsyslog/rsyslog.conf
    dest: /etc/rsyslog.conf

- name: Restart rsyslog service
  service:
    name: rsyslog
    state: restarted