- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
 
  tasks:
    - name: Install Python
      raw: test -e /usr/bin/python || (apt -y update && apt  install -y python)

    - name: ensure local user has a matching account on the host
      user:
        state: 'present'
        name: 'marius'
        shell: '/bin/bash'
        home: '/home/marius/'
        groups: sudo

    - name: ensure local user's public key is on the host
      authorized_key:
        user: "marius"
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
