Vagrant.configure('2') do |config|

	# default provider
	config.vm.provider "libvirt"
	
	config.vm.define :my_vm do |myvm| 
    		
		myvm.vm.host_name = 'myvm'
        myvm.vm.box = 'generic/ubuntu1604'
  		myvm.vm.network :private_network, ip: '10.143.20.7'

		myvm.vm.provider :libvirt do |lv|
			lv.driver = "kvm"
    	end
		
		config.vm.provision 'ansible' do |ansible|
    		ansible.playbook = 'users.yml'
  		end
  	end	

end
