- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no

  vars:
    users:
      - name: marius
        key: "{{ lookup('file', '/home/marius/Yonder/Ansible/variables-loops-and-filters/marius.pub') }}"
      - name: workshop
        key: "{{ lookup('file', '/home/marius/Yonder/Ansible/variables-loops-and-filters/workshop.key') }}"

  tasks:
      
    - name: Install Python
      raw: test -e /usr/bin/python || (apt -y update && apt  install -y python)

    - name: add users
      user:
        name: "{{ item.name }}"
        state: present
        groups: sudo
      with_items: "{{users}}"

    - name: ensure key
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ item.key + \"/n\"}}"
        state: present
      with_items: "{{users}}"